### ISSUE TITLE
upload to python package index

### ISSUE THREAD

**Issue by sangwonl** [caststack/python-mpegdash#10]

**Comment by Kobla** [comment]
I am back :-) BTW Thx for merge.

Before uploading to python package index, make a release first.
Version number should match the version in the setup.py

Thanks

**Comment by onovy** [comment]
to make downstream (debian package mantainer) happy :) please make releases as ideally signed git tags named exactly as a version. then exactly same commit publish to pypi.

this is last blocker before we can publish Debian package

Thanks.

**Comment by sangwonl** [comment]
https://pypi.python.org/pypi/mpegdash/0.1.0/

Finally, our package got uploaded to pypi. Thanks for all your contributions.

If you have any concern about the release, please feel free to let me know.

**Comment by onovy** [comment]
thanks.

Kobla prepared package:
https://anonscm.debian.org/cgit/python-modules/packages/python-mpegdash.git/
it should be uploaded to Debian in few days

**Comment by sangwonl** [comment]
@onovy @Kobla awesome. thanks!
