### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by ryandurfey** [caststack/python-mpegdash#12]
I can install in python 2.7 using "sudo pip install mpegdash", but installing using pip3 fails.  Any suggestions?

Bash$ sudo  pip3 install mpegdash
Collecting mpegdash
  Could not find a version that satisfies the requirement mpegdash (from versions: )
No matching distribution found for mpegdash

**Comment by sangwonl** [comment]
@ryandurfey Hello, 
Could you give us more details about dev environment so that we can reproduce the issue?
- linux / mac with version
- any virtual environments(pyenv or virtualenv) for python

**Comment by sangwonl** [comment]
It seems like a mistake that the proper classifiers for py3 are missing in setup.py.

**Comment by ryandurfey** [comment]
Thanks for the response, and thanks for publishing the code.  I am currently running Pyenv 3.5.1 on Mac 10.11.6.  I also run pyenv 2.7 on the same machine and it loads and works well there.

**Comment by sangwonl** [comment]
Hope #13 resolve this issue.
